config/routes.rb
Sharebox::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  match "/boxfile/index",   :as => "boxfile", :via => :get
  match "/boxfile/delete",  :as => "delete",  :via => [:get, :post]
  match "/boxfile/add",     :as => "add",     :via => :get
  match "/boxfile/upload", :as => "upload",  :via => :post

  

end

app/models/boxfile.rb
class Boxfile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boxfile_controller.rb
class BoxfileController < ApplicationController
    before_filter :authenticate_user!

    def index
        if current_user.folder.nil?
            current_user.folder = generate_random_user_folder_name
            current_user.save
        end
        @userfiles = AWS::S3::Bucket.objects(BUCKET_NAME, :prefix => current_user.folder)
    end

    def add
    end

    def upload
        begin
          AWS::S3::S3Object.store(sanitize_filename(params[:boxfile].original_filename), 
                                    params[:boxfile].read, BUCKET_NAME, :access => :public_read)
          redirect_to boxfile_path, :notice => "Your file was successfully uploaded to ShareBox"
        rescue
          redirect_to boxfile_path, :error => "Your file couldn't be uploaded to ShareBox"
        end
    end

    def delete
        if (params[:file_id])  
            AWS::S3::S3Object.find(params[:file_id], BUCKET_NAME).delete  
            redirect_to boxfile_path, :notice => params[:file_id].sub(current_user.folder + '/','') + " was deleted"
        else  
            redirect_to boxfile_path, :error => "Could not delete " + params[:file_id].sub(current_user.folder + '/','') 
        end  
    end

    def sanitize_filename(file_name)
        just_filename = File.basename(file_name)
        File.join(current_user.folder, just_filename.sub(/[^\w\.\-]/,'_'))
    end

    def generate_random_user_folder_name()
        letters = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
		return (0...8).map{ letters[rand(letters.length)] }.join
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index	
        if user_signed_in?
            redirect_to :controller => 'boxfile', :action => 'index'
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def download_url_for(userfile_key)
        AWS::S3::S3Object.url_for(userfile_key, BUCKET_NAME, :authenticated => false)
    end
end

app/helpers/boxfile_helper.rb
module BoxfileHelper

    def get_user_bucket_folder(bucket)
        path = File.join(BUCKET_NAME, current_user.folder)
        return path
    end

    

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boxfile/add.html.erb
<h2>Upload a new file:</h2>  
<%= form_tag upload_path, :method => "post", :multipart => true do %>  
    <div class="control-group">
        <div class="controls">
        <%= file_field_tag "boxfile" %>
        </div>
    </div>  
    <div class="form-actions">
        <%= submit_tag "Upload", :class => 'btn btn-primary' %>
    </div>
<% end %>  

app/views/boxfile/index.html.erb
<div class="page-header">
    <h1>Your ShareBox</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Filename</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @userfiles.each do |uf| %>
        <tr>
            <td><%= uf.key.sub(current_user.folder + '/','') %></td>
            <td>
            <%= link_to "Download", download_url_for(uf.key), :class => 'btn btn-mini' %>
            <%= link_to "Delete", "/boxfile/delete/?file_id=" + uf.key, 
                        :confirm => "Are you sure you want to delete?", :class => 'btn btn-mini btn-danger' %>
            </td>
                                        
        </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Upload a file", add_path, :class => 'btn btn-primary' %>

app/views/boxfile/upload.html.erb
<h2>Upload a new file:</h2>  
<%= form_tag upload_path, :method => "post", :multipart => true do %>  
    <p><%= file_field_tag "boxfile" %></p>  
    <p><%= submit_tag "Upload" %></p>
<% end %>  

app/views/home/index.html.erb
<h1>Welcome to ShareBox!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sharebox" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Sharebox</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete  %></li>
              <% else %>
              <li><%= link_to "Register", new_user_registration_path  %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>